ruby-on-rails/config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get  '/top', to: 'top#index'

  # TrainingDataController
  resource :training_data, only: [:new]
  post '/training_data/download', to: 'training_data#download'
  get  '/training_data/download', to: redirect('/training_data/new')

  # ScoreChartController
  resource :score_chart, only: [:new, :create], controller: :score_chart
  get '/score_chart/draw',     to: 'score_chart#draw'
  get '/score_chart/download', to: 'score_chart#download', default: { format: :csv }
  get '/score_chart',          to: redirect('/score_chart/new')
end

ruby-on-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ruby-on-rails/app/controllers/concerns/chart_manager.rb
module ChartManager
  PATH = Rails.root.join('tmp', 'downloads')

  def save_chart(filename, csv_chart)
    Dir.mkdir(PATH) unless Dir.exist?(PATH)
    File.open(PATH.join(filename), 'w') { |f| f.puts(csv_chart) }
  end

  def tmp_charts
    Dir[PATH.join('accuracy_score_chart*.csv')]
  end

  def tmp_chart
    tmp_charts.last
  end

  def matrix_chart
    CSV.open(tmp_chart) { |f| f.read } if tmp_chart
  end

  def clear_tmp_charts
    FileUtils.rm_rf(tmp_charts) if tmp_charts.any?
  end
end

ruby-on-rails/app/controllers/concerns/format.rb
module Format
  def template
    {
      id: '',
      data: {
        action: 'text',
        contexts: ['sample'],
        enabled: true,
        answers: {
          ja: []
        },
        questions: {
          ja: []
        },
        redirectFlow: '',
        redirectNode: ''
      }
    }
  end

  def to_json(training_data)
    result = Array.new
    format = template

    CSV.foreach(training_data, headers: true) { |training_datum|
      if format[:data][:answers][:ja].last == training_datum['Answer']
        format[:data][:questions][:ja] << training_datum['Question']
      else
        format      = template
        format[:id] = training_datum['ID']
        format[:data][:questions][:ja] << training_datum['Question']
        format[:data][:answers][:ja] << training_datum['Answer']
      end
      format[:data][:questions][:ja].uniq!
      result << format
    }

    JSON.pretty_generate({ qnas: result.uniq })
  end
end

ruby-on-rails/app/controllers/score_chart_controller.rb
class ScoreChartController < ApplicationController
  include ChartManager
  before_action :clear_tmp_charts, only: [:new]
  before_action :redirect_to_new_score_chart_url, only: [:draw, :download]

  # GET: /score_chart/new
  def new
    @score_chart_form = ScoreChartForm.new
  end

  # POST: /score_chart
  def create
    @score_chart_form = ScoreChartForm.new(test_params)
    if @score_chart_form.valid?
      accuracy_check_query = AccuracyCheckQuery.new(test_params)
      begin
        res_bodies = accuracy_check_query.res_bodies
      rescue SocketError
        flash[:alert] = 'Host is invalid'
        render :new and return
      end

      chart_drawer = ChartDrawer.new(test_params[:test_data], res_bodies)
      begin
        csv_chart = chart_drawer.csv
      rescue NoMethodError
        flash[:alert] = 'BotID, UserID or AccessToken is invalid'
        render :new and return
      end

      save_chart(filename, csv_chart)
      redirect_to score_chart_draw_url
    else
      render :new
    end
  end

  # GET: /score_chart/draw
  def draw
    @chart = matrix_chart
  end

  #GET: /score_chart/download
  def download
    send_file(tmp_chart, filename: filename)
  end

  private

  def test_params
    params.permit(:scheme, :host, :bot_id, :user_id, :access_token, :test_data)
  end

  def filename
    "accuracy_score_chart_#{DateTime.current.strftime('%F%T').gsub(/[:\-]/, '')}.csv"
  end

  def redirect_to_new_score_chart_url
    redirect_to new_score_chart_url and return unless tmp_chart
  end
end

ruby-on-rails/app/controllers/top_controller.rb
class TopController < ApplicationController

  # GET: /top
  def index; end
end

ruby-on-rails/app/controllers/training_data_controller.rb
class TrainingDataController < ApplicationController
  include Format

  # GET: /training_data/new
  def new
    @training_data_form = TrainingDataForm.new
  end

  # POST: /training_data/download
  def download
    @training_data_form = TrainingDataForm.new(training_params)
    if @training_data_form.valid?
      send_data(to_json(training_params[:training_data]), filename: filename)
    else
      render :new
    end
  end

  private

  def training_params
    params.permit(:training_data)
  end

  def filename
    "training_data_#{DateTime.current.strftime('%F%T').gsub(/[:\-]/, '')}.json"
  end
end

ruby-on-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby-on-rails/app/helpers/score_chart_helper.rb
module ScoreChartHelper
  def accuracy(row)
    return unless row.include?('%')
    if row.to_f == 0.0
      ''
    elsif row.to_f >= 70.0
      'excellent'
    elsif row.to_f >= 50.0
      'good'
    elsif row.to_f >= 30.0
      'bad'
    else
      'useless'
    end
  end
end

ruby-on-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Botpress Accuracy Checker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= link_to 'Top', root_path, class: 'badge' %>
    <div class="container">
      <% if flash.notice %>
        <div class="alert alert-success">
          <%= flash.notice %>
        </div>
      <% end %>
      <% if flash.alert %>
        <div class="alert alert-danger">
          <%= flash.alert %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

ruby-on-rails/app/views/score_chart/draw.html.erb
<h1>Accuracy Score Chart</h1>
<p><%= link_to 'Download Score Chart', score_chart_download_url, class: 'btn btn-primary' %></p>
<div class="scroll-table">
  <table>
    <% @chart&.each do |chart| %>
      <tr>
        <% chart&.each do |row| %>
          <th class=<%= accuracy(row) %>><%= row %></th>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

<div class="annotaion">
  <h2>Annotation</h2>
  <p class="excellent">Greater than or equal to 70.0%</p>
  <p class="good">Greater than or equal to 50.0% and less than 70.0%</p>
  <p class="bad">Greater than or equal to 30.0% and less than 50.0%</p>
  <p class="useless">Greater than or equal to 0.1% and less than 30.0%</p>
</div>

ruby-on-rails/app/views/score_chart/new.html.erb
<h1>Create Score Chart</h1>
<%= form_with url: score_chart_url do |f| %>
<%= render 'shared/errors', object: @score_chart_form %>
  <div class="form-item">
    <p><strong><%= f.label :scheme %></strong></p>
    <p><%= f.select :scheme, ['https', 'http'], { selected: 'https' } %></p>
  </div>
  <div class="form-item">
    <p><strong><%= f.label :host %></strong></p>
    <p><%= f.text_field :host, size: 50, placeholder: 'sample.com' %></p>
  </div>
  <div class="form-item">
    <p><strong><%= f.label :bot_id %></strong></p>
    <p><%= f.text_field :bot_id, size: 30, placeholder: 'sample-bot' %></p>
  </div>
  <div class="form-item">
    <p><strong><%= f.label :user_id %></strong></p>
    <p><%= f.text_field :user_id, size: 30, placeholder: 'sample-user' %></p>
  </div>
  <div class="form-item">
    <p><strong><%= f.label :access_token %></strong></p>
    <p><%= f.text_area :access_token, size: '100x5', placeholder: 'Bearer ...' %></p>
  </div>
  <div class="form-item">
    <p><strong><%= f.label :test_data %></strong></p>
    <p><%= f.file_field :test_data, accept: '.csv' %></p>
  </div>
  <div class="form-item">
    <p><%= f.submit 'Create Score Chart', class: 'btn btn-primary' %></p>
  </div>
<% end %>

ruby-on-rails/app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

ruby-on-rails/app/views/top/index.html.erb
<h1>Botpress Accuracy Checker</h1>
<ul class="list-group">
  <li class="list-group-item"><%= link_to 'Create JSON Training Data', new_training_data_path %></li>
  <li class="list-group-item"><%= link_to 'Create Score Chart', new_score_chart_path %></li>
</ul>

ruby-on-rails/app/views/training_data/new.html.erb
<h1>Create JSON Training Data</h1>
<%= form_with url: training_data_download_path, method: :post do |f| %>
<%= render 'shared/errors', object: @training_data_form %>
  <div class="container">
    <p><%= f.label :training_data %></p>
    <p><%= f.file_field :training_data, accept: '.csv' %></p>
    <p><%= f.submit 'Export JSON', class: 'btn btn-primary' %></p>
  </div>
<% end %>